let portugueseCountries = [
    { "name": "Afeganistão" },
    { "name": "Albânia" },
    { "name": "Argélia" },
    { "name": "Andorra" },
    { "name": "Angola" },
    { "name": "Antígua e Barbuda" },
    { "name": "Argentina" },
    { "name": "Armênia" },
    { "name": "Austrália" },
    { "name": "Áustria" },
    { "name": "Azerbaijão" },
    { "name": "Bahamas" },
    { "name": "Barém" },
    { "name": "Bangladesh" },
    { "name": "Barbados" },
    { "name": "Bielorrússia" },
    { "name": "Bélgica" },
    { "name": "Belize" },
    { "name": "Benin" },
    { "name": "Butão" },
    { "name": "Bolívia" },
    { "name": "Bósnia e Herzegovina" },
    { "name": "Botsuana" },
    { "name": "Brasil" },
    { "name": "Brunei" },
    { "name": "Bulgária" },
    { "name": "Burkina Faso" },
    { "name": "Birmânia" },
    { "name": "Burundi" },
    { "name": "Cabo Verde" },
    { "name": "Camboja" },
    { "name": "Camarões" },
    { "name": "Canadá" },
    { "name": "República Centro-Africana" },
    { "name": "Chade" },
    { "name": "Chile" },
    { "name": "China" },
    { "name": "Colômbia" },
    { "name": "Congo (Brazzaville)" },
    { "name": "Congo (Kinshasa)" },
    { "name": "Costa Rica" },
    { "name": "Costa do Marfim" },
    { "name": "Croácia" },
    { "name": "Cuba" },
    { "name": "Chipre" },
    { "name": "Tchéquia" },
    { "name": "Dinamarca" },
    { "name": "Diamond Princess" },
    { "name": "Djibuti" },
    { "name": "Dominica" },
    { "name": "República Dominicana" },
    { "name": "Equador" },
    { "name": "Egito" },
    { "name": "El Salvador" },
    { "name": "Guiné Equatorial" },
    { "name": "Eritreia" },
    { "name": "Estônia" },
    { "name": "Eswatini" },
    { "name": "Etiópia" },
    { "name": "Fiji" },
    { "name": "Finlândia" },
    { "name": "França" },
    { "name": "Gabão" },
    { "name": "Gâmbia" },
    { "name": "Geórgia" },
    { "name": "Alemanha" },
    { "name": "Gana" },
    { "name": "Grécia" },
    { "name": "Granada" },
    { "name": "Guatemala" },
    { "name": "Guiné" },
    { "name": "Guiné-Bissau" },
    { "name": "Guiana" },
    { "name": "Haiti" },
    { "name": "Vaticano" },
    { "name": "Honduras" },
    { "name": "Hungria" },
    { "name": "Islândia" },
    { "name": "Índia" },
    { "name": "Indonésia" },
    { "name": "Iran" },
    { "name": "Iraque" },
    { "name": "Irlanda" },
    { "name": "Israel" },
    { "name": "Itália" },
    { "name": "Jamaica" },
    { "name": "Japão" },
    { "name": "Jordânia" },
    { "name": "Cazaquistão" },
    { "name": "Quênia" },
    { "name": "Coreia do Sul" },
    { "name": "Kosovo" },
    { "name": "Kuwait" },
    { "name": "Quirguistão" },
    { "name": "Laos" },
    { "name": "Letônia" },
    { "name": "Líbano" },
    { "name": "Libéria" },
    { "name": "Líbia" },
    { "name": "Liechtenstein" },
    { "name": "Lituânia" },
    { "name": "Luxemburgo" },
    { "name": "MS Zaandam" },
    { "name": "Madagáscar" },
    { "name": "Malawi" },
    { "name": "Malásia" },
    { "name": "Maldivas" },
    { "name": "Mali" },
    { "name": "Malta" },
    { "name": "Mauritânia" },
    { "name": "Maurícia" },
    { "name": "México" },
    { "name": "Moldova" },
    { "name": "Mônaco" },
    { "name": "Mongólia" },
    { "name": "Montenegro" },
    { "name": "Marrocos" },
    { "name": "Moçambique" },
    { "name": "Namíbia" },
    { "name": "Nepal" },
    { "name": "Países Baixos" },
    { "name": "Nova Zelândia" },
    { "name": "Nicarágua" },
    { "name": "Níger" },
    { "name": "Nigéria" },
    { "name": "Macedônia do Norte" },
    { "name": "Noruega" },
    { "name": "Omã" },
    { "name": "Paquistão" },
    { "name": "Panamá" },
    { "name": "Papua Nova Guiné" },
    { "name": "Paraguai" },
    { "name": "Peru" },
    { "name": "Filipinas" },
    { "name": "Polônia" },
    { "name": "Portugal" },
    { "name": "Catar" },
    { "name": "Romênia" },
    { "name": "Rússia" },
    { "name": "Ruanda" },
    { "name": "São Cristóvão e Nevis" },
    { "name": "Santa Lúcia" },
    { "name": "São Vicente e Granadinas" },
    { "name": "San Marino" },
    { "name": "São Tomé e Príncipe" },
    { "name": "Arábia Saudita" },
    { "name": "Senegal" },
    { "name": "Sérvia" },
    { "name": "Seychelles" },
    { "name": "Serra Leoa" },
    { "name": "Cingapura" },
    { "name": "Eslováquia" },
    { "name": "Eslovênia" },
    { "name": "Somália" },
    { "name": "África do Sul" },
    { "name":" Sudão do Sul" },
    { "name": "Espanha" },
    { "name": "Sri Lanka" },
    { "name": "Sudão" },
    { "name": "Suriname" },
    { "name": "Suécia" },
    { "name": "Suíça" },
    { "name": "Síria" },
    { "name": "Taiwan" },
    { "name": "Tanzânia" },
    { "name": "Tailândia" },
    { "name": "Timor-Leste" },
    { "name": "Ir" },
    { "name" : "Trindade e Tobago" },
    { "name": "Tunísia" },
    { "name": "Peru" },
    { "name": "NOS" },
    { "name": "Uganda" },
    { "name": "Ucrânia" },
    { "name": "Emirados Árabes Unidos" },
    { "name": "Reino Unido" },
    { "name": "Uruguai" },
    { "name": "Usbequistão" },
    { "name": "Venezuela" },
    { "name": "Vietnã" },
    { "name": "Cisjordânia e Gaza" },
    { "name": "Saara Ocidental" },
    { "name": "Iémen" },
    { "name": "Zâmbia" },
    { "name": "Zimbábue" },
];

export default portugueseCountries;